### ISSUE TITLE
Adding keywords to ubuntu-scope-nearby

### ISSUE THREAD

**Issue by gang65** [weeman1337/ubuntu-scope-aroundu#1]
It will be great to integrate keywords into this scope.
It will allows to highly integrate with "NearBy" scope aggregator.

I would recommend to use following keywords: "nearby, poi, drink, food, business"
More information is available at:
https://developer.ubuntu.com/en/scopes/guides/scope-keywords/

**Comment by weeman1337** [comment]
Thanks for the report. I moved this project to launchpad. You can follow the status of the keyword support on https://blueprints.launchpad.net/aroundu/+spec/keyword-support .
